comment:
  on-update: recreate
  header: "Automated PR Review Reminder"
  footer: "Thank you for contributing!"
  snippets:
    - id: env-file-changed
      files:
        - '**/.env'
      body: |
        :warning: You've modified a `.env` file. Please ensure that any new environment variables are communicated to the infrastructure team for proper setup in all environments.
