comment:
  on-update: recreate
  header: |
    :wave: Hello @{{ prAuthor }}!

  footer: |
    ---
    Automated comment created by [PR Commenter](https://github.com/exercism/pr-commenter-action) :robot:.
  snippets:
    - id: env-file-changed
      files:
        - '**/.env.*'
        - '**/.dev.env'
      body: |
        :eyes: It looks like you're changing a `.env` file.

        Please ensure any new environment variables are communicated to the infrastructure team for proper setup in their target environments.
        
        /cc @waterlegacy0
