name: handle-special-characters

on:
  push:
    branches:
      - master

jobs:
  test-commit-message:
    runs-on: ubuntu-latest
    env:
      UPDATE_DESCRIPTION: ${{ github.event.head_commit.message }}
    steps:
      - uses: actions/checkout@v4

      - name: Display Commit Message
        run: |
          echo "Commit Message: $UPDATE_DESCRIPTION"

      - name: Simulate No Syntax Error
        run: |
          echo "Commit Message: ${{ env.UPDATE_DESCRIPTION }}"
          echo "Simulating no syntax error"
          eval "echo ${UPDATE_DESCRIPTION}"
