name: handle-special-characters

on:
  push:
    branches:
      - master

jobs:
  test-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Env Var from Commit Message
        run: |
          update_description=$(printf '%q' "${{ github.event.head_commit.message }}" | head -1)
          echo "UPDATE_DESCRIPTION=${update_description}" >> $GITHUB_ENV
      - name: Simulate No Syntax Error
        run: |
          echo "Commit Message: ${{ env.UPDATE_DESCRIPTION }}"
          echo "Simulating no syntax error"
          eval "echo ${UPDATE_DESCRIPTION}"
