name: handle-special-characters

on:
  push:
    branches:
      - master

jobs:
  test-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Env Var from Commit Message
        run: |

          printf -v safe_description "UPDATE_DESCRIPTION=%s" "${{ github.event.head_commit.message }}"
          echo $safe_description | head -1 >> $GITHUB_ENV


      - name: Decode and Use Description
        run: |
          # Assuming UPDATE_DESCRIPTION in $GITHUB_ENV contains the base64 encoded message
          decoded_message=$(echo "$UPDATE_DESCRIPTION" | base64 --decode)
          echo "Decoded Message: $decoded_message"
      
      - name: Display Commit Message
        run: |
          echo "Commit Message: ${{ env.UPDATE_DESCRIPTION }}"
      - name: Simulate No Syntax Error
        run: |
          echo "Simulating no syntax error"
          eval "echo ${UPDATE_DESCRIPTION}"
          eval "echo ${decoded_message}"
          eval "echo ${safe_description}"
