name: replicate-issue

on:
  push:
    branches:
      - master

jobs:
  test-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Env Var from Commit Message
        run: |
          echo "UPDATE_DESCRIPTION=${{ github.event.head_commit.message }}" | head -1 >> $GITHUB_ENV
      - name: Simulate Syntax Error
        run: |
          echo "Commit Message: ${{ env.UPDATE_DESCRIPTION }}"
          echo "Simulating syntax error"
          eval "echo ${UPDATE_DESCRIPTION}"

