name: Test Commit Message Handling

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Update Request
        run: |
          IMAGE_REGISTRY=dummy.registry
          image_tag=latest
          formatted_ref=1234567abcdef
          
          images_to_update=(
              "$IMAGE_REGISTRY/test/repo:$image_tag"
              "$IMAGE_REGISTRY/test/repo-worker:$image_tag"
          )

          oldIFS=$IFS
          IFS=","
          echo "PROJECT_IMAGES=${images_to_update[*]}" >> $GITHUB_ENV
          IFS=$oldIFS

          head_commit_message="${{ github.event.pull_request.title }}"
          echo "UPDATE_DESCRIPTION_1=${head_commit_message}" | head -1 >> $GITHUB_ENV


          echo "UPDATE_DESCRIPTION_2=${{ github.event.pull_request.title }}" | head -1 >> $GITHUB_ENV
          echo "UPDATE_RELEASE=${formatted_ref:0:7}" >> $GITHUB_ENV


      - name: Display environment variables
        run: |
          echo "PROJECT_IMAGES=${PROJECT_IMAGES}"
          echo "UPDATE_DESCRIPTION_1=${UPDATE_DESCRIPTION_1}"
          echo "UPDATE_DESCRIPTION_2=${UPDATE_DESCRIPTION_2}"

          echo "UPDATE_RELEASE=${UPDATE_RELEASE}"
        env:
          PROJECT_IMAGES: ${{ env.PROJECT_IMAGES }}
          UPDATE_DESCRIPTION_1: ${{ env.UPDATE_DESCRIPTION_1 }}
          UPDATE_DESCRIPTION_2: ${{ env.UPDATE_DESCRIPTION_2 }}
          UPDATE_RELEASE: ${{ env.UPDATE_RELEASE }}
