name: PR Labeler

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, unlabeled]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        sync-labels: true
