name: Test Mirror ECR Conditionals

on:
  workflow_dispatch:
    inputs:
      to-ecr-tag:
        description: 'Tag for the ECR image'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Simulate ARM64 Pull
        if: ${{ contains(inputs.to-ecr-tag, 'arm') }}
        run: echo "Simulating pull to ARM64 for ${{ inputs.to-ecr-tag }}"

      - name: Simulate Default Pull
        if: ${{ !contains(inputs.to-ecr-tag, 'arm') }}
        run: echo "Simulating pull to Default for ${{ inputs.to-ecr-tag }}"
      
      - name: Simulate Tag and Push
        run: echo "Simulating docker tag and push.... "
