name: Update PR Labels

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Update PR Labels
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.payload.pull_request.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const reviewState = context.payload.review.state;
          
          // Define label to add and remove based on the review state
          let labelToAdd = '';
          let labelToRemove = 'requires review'; // Default label to remove
          
          if (reviewState === 'approved') {
            labelToAdd = 'Approved';
          } else if (reviewState === 'changes requested') {
            labelToAdd = 'Changes Requested';
          } else if (reviewState === 'dismissed') {
            labelToAdd = 'requires review';
            labelToRemove = 'Changes Requested';
          }
          
          // Remove label
          try {
            await github.rest.issues.removeLabel({
              owner,
              repo,
              issue_number: prNumber,
              name: labelToRemove
            });
            console.log(`Label '${labelToRemove}' removed`);
          } catch (error) {
            if (error.status !== 404) {
              throw error;
            }
            console.log(`Label '${labelToRemove}' not found, skipping.`);
          }
          
          // Add label
          try {
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: [labelToAdd]
            });
            console.log(`Label '${labelToAdd}' added`);
          } catch (error) {
            throw error;
          }
