name: auto-pr-update-label

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Update PR Labels
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.payload.pull_request.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const reviewState = context.payload.review.state;

          let labelsUpdated = false;
          let labelToAdd = '';
          let labelToRemove = '';

          if (reviewState === 'approved') {
            labelToAdd = 'approved';
            labelToRemove = 'requires review';

          } else if (reviewState === 'changes_requested') {
            labelToAdd = 'changes requested';
            labelToRemove = 'requires review';

          } else if (reviewState === 'dismissed') {
            labelToAdd = 'requires review';
            labelToRemove = 'changes requested';
          }

          // Check if labelToRemove exists before attempting to remove it
          if (labelToRemove) {
            try {
              await github.rest.issues.removeLabel({
                owner,
                repo,
                issue_number: prNumber,
                name: labelToRemove
              });
              console.log(`Label '${labelToRemove}' removed`);
              labelsUpdated = true;

            } catch (error) {
              if (error.status !== 404) {
                throw error;
              }
              console.log(`Label '${labelToRemove}' not found, skipping.`);
            }
          }
          
          // Check if labelToAdd is non-empty before attempting to add it
          if (labelToAdd) {
            try {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: prNumber,
                labels: [labelToAdd]
              });
              console.log(`Label '${labelToAdd}' added`);
              labelsUpdated = true;

            } catch (error) {
              throw error;
            }
          }

          if (!labelsUpdated) {
            console.log("No new review action, no labels updated")
          }